### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by fatkhrus** [mkeras/EmbeddedSparkplugNode#5]
Try to use on ESP8266. It seems it's not correctly encoding protobuf protocol.

**Comment by ryanbateman** [comment]
I have the same issue on an ESP32 - messages do not appear to be decodable using standard Sparkplug decoder libraries (Eclipse Tahu) which are able to decode other Sparkplug messages. Odd.

**Comment by mkeras** [comment]
would you share the code that produces the malformed payload? I would like to investigate and try and find the bug in this library.

Thanks, Michael

**Comment by ryanbateman** [comment]
@mkeras Sure, I'll upload it and link it here this evening.

**Comment by ryanbateman** [comment]
@mkeras Apologies for the delay. Here's [a gist with the code](https://gist.github.com/ryanbateman/e15b1803ad1d551edd51cfe64c042367). I've validated other Sparkplug payloads on the same broker (sent via the node-red Sparkplug plugin) can be parsed via MQTT.fx's Sparkplug plugin. Unfortunately it can't do the same for Sparkplug messages sent via the code above. 
I am sure I am missing something simple, and I appreciate your library is in alpha, so any input is helpful and appreciated. 

(For context, the project is using a [m5Atom ](https://thepihut.com/products/atom-matrix-esp32-development-kit) with a servo board, running two servos, which I'd like to control and monitor as a Sparkplug node simply for my own curiosity's sake, and because it relates somewhat to my job at HiveMQ, an MQTT Broker developer.)

**Comment by ryanbateman** [comment]
I managed to resolve this, in the end. The issue (for me) was the actual MQTT library publishing. I had to specify the buffer length to get it to accurately publish. I change this line:
` mqttClient.publish(topic, (char*) buffer);`
to this:
 `mqttClient.publish(topic, (char*) buffer, buffer_length);`

Now it's all working well. Thank you again!

**Comment by mkeras** [comment]
Awesome, glad to here it! That part is something that stumped me for a while when I was making testing the functions, which led to adding that buffer_length option to the mqtt publish of the mqtt client.
